name: Build and Publish
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Pack extension
        uses: thedoctor0/zip-release@master
        with:
          filename: 'click-to-call.zip'
          exclusions: '*.git*'

      - name: Upload to Chrome Webstore
        uses: trmcnvn/chrome-addon@master
        with:
          extension: gcmffhldcmblemadbaooobdopcbjkcpc
          zip: click-to-call.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        continue-on-error: true

      - name: Upload to Firefox Browser Add-ons
        uses: trmcnvn/firefox-addon@master
        with:
          uuid: '{88c8dc86-a910-413f-ab32-41bd28d7f2c7}'
          xpi: click-to-call.zip
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
        continue-on-error: true
